export function getHandbookMarkdown(): string {
  return [
    "# Orchestrator Plugin",
    "",
    "## Quick Start",
    "1. Spawn a worker: `/orchestrator.spawn.docs` or `/orchestrator.spawn.vision`",
    "2. Send work: `ask_worker({ workerId: 'docs', message: 'Find docs for X' })`",
    "3. Or auto-route: `delegate_task({ task: 'Research best practices for Y' })`",
    "",
    "## Commands",
    "| Command | Description |",
    "|---------|-------------|",
    "| `orchestrator.status` | Show workers, profiles, and config |",
    "| `orchestrator.models` | List available models from OpenCode |",
    "| `orchestrator.profiles` | List worker profiles (vision, docs, coder, etc.) |",
    "| `orchestrator.workers` | List running workers |",
    "| `orchestrator.spawn.<id>` | Spawn a worker (e.g. spawn.docs, spawn.vision) |",
    "",
    "## Tools (8 total)",
    "| Tool | Purpose |",
    "|------|---------|",
    "| `spawn_worker` | Start a worker with a profile |",
    "| `ask_worker` | Send a message to a specific worker |",
    "| `delegate_task` | Auto-route task to best worker |",
    "| `list_workers` | List running workers (or get details with workerId) |",
    "| `stop_worker` | Stop a running worker |",
    "| `list_profiles` | Show available worker profiles |",
    "| `list_models` | Show available models |",
    "| `orchestrator_status` | Show config and status |",
    "",
    "## Built-in Profiles",
    "- `vision` — Image/screenshot analysis",
    "- `docs` — Documentation research",
    "- `coder` — Code implementation",
    "- `architect` — System design and planning",
    "- `explorer` — Fast codebase searches",
    "",
    "## Examples",
    "```",
    "// Spawn and use docs worker",
    "spawn_worker({ profileId: 'docs' })",
    "ask_worker({ workerId: 'docs', message: 'Find React hooks docs' })",
    "",
    "// Auto-route a task",
    "delegate_task({ task: 'Analyze this error screenshot', requiresVision: true })",
    "",
    "// Get worker details",
    "list_workers({ workerId: 'docs' })",
    "```",
    "",
  ].join("\n");
}

