import type { SdkAction } from "../sdk-action-types";
import { templateForSessionId } from "../sdk-action-types";

export const sessionActions: SdkAction[] = [
  {
    id: "session.list",
    group: "Sessions",
    label: "List Sessions",
    template: {},
    run: (client, input) => client.session.list(input),
  },
  {
    id: "session.create",
    group: "Sessions",
    label: "Create Session",
    template: { body: { title: "New session" } },
    run: (client, input) => client.session.create(input),
  },
  {
    id: "session.get",
    group: "Sessions",
    label: "Get Session",
    template: templateForSessionId(),
    run: (client, input) => client.session.get(input),
  },
  {
    id: "session.update",
    group: "Sessions",
    label: "Update Session",
    template: { ...templateForSessionId(), body: { title: "Updated title" } },
    run: (client, input) => client.session.update(input),
  },
  {
    id: "session.delete",
    group: "Sessions",
    label: "Delete Session",
    template: templateForSessionId(),
    run: (client, input) => client.session.delete(input),
  },
  {
    id: "session.status",
    group: "Sessions",
    label: "Session Status",
    template: templateForSessionId(),
    run: (client, input) => client.session.status(input),
  },
  {
    id: "session.children",
    group: "Sessions",
    label: "Session Children",
    template: templateForSessionId(),
    run: (client, input) => client.session.children(input),
  },
  {
    id: "session.todo",
    group: "Sessions",
    label: "Session Todo",
    template: templateForSessionId(),
    run: (client, input) => client.session.todo(input),
  },
  {
    id: "session.init",
    group: "Sessions",
    label: "Session Init",
    template: {
      path: { id: "<session-id>" },
      body: { providerID: "opencode", modelID: "gpt-5-nano", messageID: "<message-id>" },
    },
    run: (client, input) => client.session.init(input),
  },
  {
    id: "session.fork",
    group: "Sessions",
    label: "Session Fork",
    template: { path: { id: "<session-id>" }, body: { messageID: "<message-id>" } },
    run: (client, input) => client.session.fork(input),
  },
  {
    id: "session.abort",
    group: "Sessions",
    label: "Session Abort",
    template: templateForSessionId(),
    run: (client, input) => client.session.abort(input),
  },
  {
    id: "session.share",
    group: "Sessions",
    label: "Session Share",
    template: templateForSessionId(),
    run: (client, input) => client.session.share(input),
  },
  {
    id: "session.unshare",
    group: "Sessions",
    label: "Session Unshare",
    template: templateForSessionId(),
    run: (client, input) => client.session.unshare(input),
  },
  {
    id: "session.diff",
    group: "Sessions",
    label: "Session Diff",
    template: templateForSessionId(),
    run: (client, input) => client.session.diff(input),
  },
  {
    id: "session.summarize",
    group: "Sessions",
    label: "Session Summarize",
    template: templateForSessionId(),
    run: (client, input) => client.session.summarize(input),
  },
  {
    id: "session.messages",
    group: "Sessions",
    label: "Session Messages",
    template: templateForSessionId(),
    run: (client, input) => client.session.messages(input),
  },
  {
    id: "session.message",
    group: "Sessions",
    label: "Session Message",
    template: { path: { id: "<session-id>", messageID: "<message-id>" } },
    run: (client, input) => client.session.message(input),
  },
  {
    id: "session.prompt",
    group: "Sessions",
    label: "Session Prompt",
    template: {
      path: { id: "<session-id>" },
      body: { parts: [{ type: "text", text: "Hello from SDK" }] },
    },
    run: (client, input) => client.session.prompt(input),
  },
  {
    id: "session.promptAsync",
    group: "Sessions",
    label: "Session Prompt Async",
    template: {
      path: { id: "<session-id>" },
      body: { parts: [{ type: "text", text: "Hello async" }] },
    },
    run: (client, input) => client.session.promptAsync(input),
  },
  {
    id: "session.command",
    group: "Sessions",
    label: "Session Command",
    template: { path: { id: "<session-id>" }, body: { command: "help", arguments: "" } },
    run: (client, input) => client.session.command(input),
  },
  {
    id: "session.shell",
    group: "Sessions",
    label: "Session Shell",
    template: { path: { id: "<session-id>" }, body: { agent: "shell", command: "pwd" } },
    run: (client, input) => client.session.shell(input),
  },
  {
    id: "session.revert",
    group: "Sessions",
    label: "Session Revert",
    template: { path: { id: "<session-id>" }, body: { messageID: "<message-id>" } },
    run: (client, input) => client.session.revert(input),
  },
  {
    id: "session.unrevert",
    group: "Sessions",
    label: "Session Unrevert",
    template: templateForSessionId(),
    run: (client, input) => client.session.unrevert(input),
  },
];
