export function getHandbookMarkdown(): string {
  return [
    "# Orchestrator Plugin",
    "",
    "## Quick Start",
    "1. Start a task: `task_start({ kind: 'worker', workerId: 'docs', task: 'Find docs for X' })`",
    "2. Await it: `task_await({ taskId: '<taskId>' })`",
    "3. Or auto-route: `task_start({ kind: 'auto', task: 'Research best practices for Y' })`",
    "",
    "## Commands",
    "| Command | Description |",
    "|---------|-------------|",
    "| `orchestrator.status` | Show workers, profiles, and config |",
    "| `orchestrator.models` | List available models from OpenCode |",
    "| `orchestrator.profiles` | List worker profiles (vision, docs, coder, etc.) |",
    "| `orchestrator.workers` | List running workers |",
    "| `orchestrator.output` | Show recent tasks + logs |",
    "| `orchestrator.workflows` | List workflows |",
    "| `orchestrator.boomerang` | Run RooCode boomerang workflow |",
    "",
    "## Tools (5 total)",
    "| Tool | Purpose |",
    "|------|---------|",
    "| `task_start` | Start a worker/workflow task (async) |",
    "| `task_await` | Await a taskId and get the result |",
    "| `task_peek` | Check task status without waiting |",
    "| `task_list` | List recent tasks |",
    "| `task_cancel` | Cancel a running task (best-effort) |",
    "",
    "## Built-in Profiles",
    "- `vision` — Image/screenshot analysis",
    "- `docs` — Documentation research",
    "- `coder` — Code implementation",
    "- `architect` — System design and planning",
    "- `explorer` — Fast codebase searches",
    "",
    "## Examples",
    "```",
    "// Start and await a docs task",
    "task_start({ kind: 'worker', workerId: 'docs', task: 'Find React hooks docs' })",
    "task_await({ taskId: '<taskId>' })",
    "",
    "// Auto-route a task (vision picked automatically if you attach an image)",
    "task_start({ kind: 'auto', task: 'Analyze this error screenshot', attachments: [...] })",
    "task_await({ taskId: '<taskId>' })",
    "```",
    "",
  ].join("\n");
}
